# Generated by Django 3.1.4 on 2020-12-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tables', '0002_auto_20201223_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyroom',
            name='time_table',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='time_table',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period',
        ),
        migrations.AddField(
            model_name='timetable',
            name='study_room',
            field=models.OneToOneField(help_text='반', null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tables.studyroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('MATH', 'MATH'), ('ENGLISH', 'ENGLISH'), ('HISTORY', 'HISTORY')], help_text='과목', max_length=30),
        ),
        migrations.CreateModel(
            name='TimeTableRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(help_text='교시')),
                ('day_of_week', models.CharField(help_text='요일', max_length=30)),
                ('time_table', models.ForeignKey(help_text='시간표', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_table_time_table_records', to='time_tables.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='time_table_record',
            field=models.ForeignKey(help_text='단위시간표', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_table_record_subjects', to='time_tables.timetablerecord'),
        ),
    ]
